name: ${PROJECT_NAME}

services:
  app:
    build: .
    container_name: ${PROJECT_NAME}_app
    restart: no
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    container_name: ${PROJECT_NAME}_db
    restart: no
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${PROJECT_NAME}_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ADMIN_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: