"""Update document  model

Revision ID: 03157b18d2f2
Revises: 7a2f2be78e4c
Create Date: 2026-06-14 16:47:58.961517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03157b18d2f2'
down_revision: Union[str, Sequence[str], None] = '7a2f2be78e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'access_only_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'access_only_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
