"""Add document_member model

Revision ID: 737d14261a36
Revises: dcfca697e778
Create Date: 2026-06-13 16:21:42.013306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737d14261a36'
down_revision: Union[str, Sequence[str], None] = 'dcfca697e778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_authors',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_authors_document_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('document_authors_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'document_id', name=op.f('document_authors_pkey'))
    )
    # ### end Alembic commands ###
