"""Update document  model

Revision ID: 7a2f2be78e4c
Revises: 737d14261a36
Create Date: 2026-06-14 16:45:56.248225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2f2be78e4c'
down_revision: Union[str, Sequence[str], None] = '737d14261a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('access_only_me', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'access_only_me')
    # ### end Alembic commands ###
