"""Add document model

Revision ID: e6c926cc3d96
Revises: adff5ed1ff27
Create Date: 2026-05-25 13:07:24.086488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c926cc3d96'
down_revision: Union[str, Sequence[str], None] = 'adff5ed1ff27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'name')
    # ### end Alembic commands ###
